// @flow

type TypeTransOne = {
    "confirmed": string,
    "chainId": string,
    "abi": any,
    "streamId": string,
    "tag": string,
    "retries": string,
    "block": {
        "number": string,
        "hash": string,
        "timestamp": string,
    },
    createdAt: string,
    "logs": any,
    txsHash: any,
    "txs":  {
        "hash": string,
        "gas": string,
        "gasPrice": string,
        "nonce": string,
        "input": string,
        "transactionIndex": string,
        "fromAddress": string,
        "toAddress": string,
        "value": string,
        "type": string,
        "v": string,
        "r": string,
        "s": string,
        "receiptCumulativeGasUsed": string,
        "receiptGasUsed": string,
        "receiptContractAddress": string,
        "receiptRoot": string,
        "receiptStatus": string,
    },
    "txsInternal": any,
    "erc20Transfers": any,
    "erc20Approvals": any,
    "nftTokenApprovals": any,
    "nftApprovals": {
        "ERC721": any,
        "ERC1155": any,
    },
    "nftTransfers": any,
    "nativeBalances": any,
}
